networks:
  production:
    external: true
    name: production

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "1000:1000"  # Garante que o container rode com um usuário não root
    environment:
      - GF_SECURITY_ADMIN_USER=youemail@youdomain.com  # Define usuário admin
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword  # Defina uma senha segura
      - GF_SERVER_DOMAIN=grafana.youdomain.com  # Domínio usado no Traefik
      - GF_SERVER_ROOT_URL=https://grafana.youdomain.com  # URL base correta para evitar erros de proxy reverso
      - GF_AUTH_ANONYMOUS_ENABLED=false  # Desativa acesso anônimo
      - GF_AUTH_DISABLE_LOGIN_FORM=false  # Mantém o login ativado
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.youdomain.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

volumes:
  grafana_data:
    driver: local
    name: grafana_data