global:
  scrape_interval: 15s  # Coleta métricas a cada 15 segundos

scrape_configs:
 
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['82.25.66.103:9100']  # Se o Prometheus estiver na mesma máquina que o Node Exporter

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']




