global:
  scrape_interval: 15s 

scrape_configs:
 
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'soketi'
    static_configs:
      - targets: ['soketi:6001']

