networks:
  applications:
    external: true
    name: applications
  databases:
    external: true
    name: databases
  production:
    external: true
    name: production
services:
  rails:
    image: chatwoot/chatwoot:latest
    container_name: rails
    env_file: .env
    volumes:
      - /data/storage:/app/storage
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    networks:
      - applications
      - databases
      - production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatwoot.rule=Host(`chatwoot.yourdomain.com`)"
      - "traefik.http.routers.chatwoot.entrypoints=websecure"
      - "traefik.http.services.chatwoot.loadbalancer.server.port=3000"
      - "traefik.docker.network=production"

  sidekiq:
    image: chatwoot/chatwoot:latest
    container_name: sidekiq
    env_file: .env
    volumes:
      - /data/storage:/app/storage
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    restart: always
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    networks:
      - applications
      - databases
      - production
