networks:
  monitoring:
    external: true
    name: monitoring

services:  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    labels:
      # Habilita descoberta do container
      - "traefik.enable=true"
      # Habilita a rota do traefik
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.tramacolorida.com.br`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      # Habilita o service do traefik (Exposer a porta interna do prometheus)
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      # Habilita o middleware de segurança
      - "traefik.http.middlewares.prometheus-auth.basicauth.users=admin:$$2y$05$$CWW9TIuG4ZlK9RtBnoObYengW8/TImy7Cqfd5T0sPJpbpb0O9bCtG"
      - "traefik.http.routers.prometheus.middlewares=prometheus-auth"
    networks:
      - monitoring



    