name: "Deploy Infra"
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Deploy com rsync (somente arquivos alterados)"
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /root/infra

      - name: "Rsync para servidor remoto"
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/infra
        env:
          RSYNC_RSH: ssh
        shell: bash

      - name: "Apagar chave temporária"
        run: rm -f ~/.ssh/deploy_key
