name: "Deploy Infra"
on:
  push:
    branches:
      - Main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Copy Files"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_TEST }}
          username: ${{ secrets.USERNAME_TEST }}
          key: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
          source: "."
          target: "."
